import { Feather, Ionicons } from "@expo/vector-icons";
import { useState } from "react";
import { ActivityIndicator, Modal, Pressable, ScrollView, Text, TextInput, View } from "react-native";

import { AnimatedPressable } from "@/components/AnimatedPressable";
import { colors } from "@/constants/theme";
import { useTaskStore } from "@/store/useTaskStore";
import type { Task } from "@/types/task";

/**
 * The "AI Breakdown" card over a running session: the task's steps, which
 * can be checked off, regenerated by the AI, or added to by hand.
 */
export function BreakdownSheet({
  visible,
  task,
  status,
  onRegenerate,
  onToggleStep,
  onClose,
}: {
  visible: boolean;
  task: Task;
  status: "idle" | "loading" | "error";
  onRegenerate: () => void;
  /** Goes through the session runner, so finishing the last step advances the session. */
  onToggleStep: (subtaskId: string) => void;
  onClose: () => void;
}) {
  const addSubtask = useTaskStore((state) => state.addSubtask);
  const [addingStep, setAddingStep] = useState(false);
  const [stepDraft, setStepDraft] = useState("");

  const steps = task.subtasks?.slice().sort((a, b) => a.order - b.order) ?? [];
  const isLoading = status === "loading";

  const handleAddStep = () => {
    const label = stepDraft.trim();
    if (label) addSubtask(task.id, label);
    setStepDraft("");
    setAddingStep(false);
  };

  return (
    <Modal visible={visible} transparent animationType="fade" onRequestClose={onClose}>
      <Pressable className="flex-1 justify-center bg-black/70 px-2.5 py-10" onPress={onClose}>
        <Pressable
          onPress={() => {}}
          className="rounded-[28px] border border-white/10 bg-charcoal-800 p-6"
          style={{ maxHeight: "100%" }}
        >
          <View className="flex-row items-start justify-between gap-4">
            <View className="flex-1 gap-1.5">
              <Text className="eyebrow text-orange-500">AI BREAKDOWN</Text>
              <Text className="text-card-title text-ink-charcoal">{task.title}</Text>
            </View>
            <AnimatedPressable
              onPress={onClose}
              accessibilityRole="button"
              accessibilityLabel="Close AI breakdown"
              className="h-10 w-10 items-center justify-center rounded-full bg-white/10"
            >
              <Feather name="x" size={20} color={colors.ink.charcoalMuted} />
            </AnimatedPressable>
          </View>

          <View className="mt-5 flex-row items-center justify-between gap-3">
            <Text className="font-grotesk-medium text-[15px] text-ink-charcoal-muted">
              {steps.length} {steps.length === 1 ? "step" : "steps"}
            </Text>
            <AnimatedPressable
              onPress={onRegenerate}
              disabled={isLoading}
              accessibilityRole="button"
              className="flex-row items-center gap-2 rounded-2xl bg-orange-500 px-4 py-2"
              style={isLoading ? { opacity: 0.75 } : undefined}
            >
              {isLoading ? (
                <ActivityIndicator size="small" color={colors.cream[50]} />
              ) : (
                <Ionicons name="sparkles-outline" size={18} color={colors.cream[50]} />
              )}
              <Text className="font-grotesk-bold text-[15px] text-cream-50">
                {isLoading ? "Generating…" : "Regenerate"}
              </Text>
            </AnimatedPressable>
          </View>

          {status === "error" ? (
            <Text className="mt-3 font-grotesk-medium text-sm text-overdue-500">
              Couldn&apos;t reach the AI. Check your connection and try again.
            </Text>
          ) : null}

          <View className="mt-4 h-px bg-white/10" />

          <ScrollView
            style={{ flexGrow: 0, marginTop: 20 }}
            contentContainerStyle={{ gap: 10 }}
            keyboardShouldPersistTaps="handled"
            showsVerticalScrollIndicator={false}
          >
            {steps.length === 0 && isLoading ? (
              <View className="flex-row items-center justify-center gap-2.5 py-6">
                <ActivityIndicator size="small" color={colors.orange[500]} />
                <Text className="font-grotesk-medium text-[15px] text-ink-charcoal-muted">
                  Breaking this task down…
                </Text>
              </View>
            ) : null}

            {steps.map((step) => {
              const done = step.status === "completed";
              return (
                <AnimatedPressable
                  key={step.id}
                  onPress={() => onToggleStep(step.id)}
                  scaleTo={0.98}
                  accessibilityRole="checkbox"
                  accessibilityState={{ checked: done }}
                  className="flex-row items-center gap-3.5 rounded-2xl border border-white/10 bg-white/5 px-4 py-4"
                >
                  <View
                    className={
                      done
                        ? "h-5 w-5 items-center justify-center rounded-md bg-success-500"
                        : "h-5 w-5 rounded-md border-2 border-white/25"
                    }
                  >
                    {done ? <Feather name="check" size={12} color={colors.cream[50]} /> : null}
                  </View>
                  <Text
                    className={
                      done
                        ? "flex-1 font-grotesk-medium text-[15px] leading-5 text-ink-charcoal-muted line-through"
                        : "flex-1 font-grotesk-medium text-[15px] leading-5 text-ink-charcoal"
                    }
                  >
                    {step.label}
                  </Text>
                </AnimatedPressable>
              );
            })}

            {addingStep ? (
              <View className="rounded-2xl border border-dashed border-white/20 px-4 py-2">
                <TextInput
                  value={stepDraft}
                  onChangeText={setStepDraft}
                  onSubmitEditing={handleAddStep}
                  placeholder="Describe the step…"
                  placeholderTextColor={colors.ink.charcoalMuted}
                  returnKeyType="done"
                  autoFocus
                  className="py-1.5 font-grotesk-medium text-[15px] text-ink-charcoal"
                />
              </View>
            ) : (
              <AnimatedPressable
                onPress={() => setAddingStep(true)}
                scaleTo={0.98}
                accessibilityRole="button"
                className="flex-row items-center justify-center gap-2 rounded-2xl border border-dashed border-white/20 py-3.5"
              >
                <Feather name="plus" size={18} color={colors.orange[500]} />
                <Text className="font-grotesk-medium text-[15px] text-ink-charcoal-muted">Add step</Text>
              </AnimatedPressable>
            )}
          </ScrollView>
        </Pressable>
      </Pressable>
    </Modal>
  );
}
